controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

error404:
    path: /error404
    controller: App\Controller\HomeController::notFound
